# ============================================================
#  Stage 0 — base: shared Node setup
# ============================================================
FROM node:20-alpine AS base

# libc6-compat is required on Alpine for certain Node.js binaries.
# See: github.com/nodejs/docker-node#nodealpine
RUN apk add --no-cache libc6-compat wget && \
    npm install -g pnpm

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# ============================================================
#  Stage 1 — deps: install node_modules
# ============================================================
FROM base AS deps

# Copy manifests first — node_modules is only rebuilt when
# package.json or lockfile actually changes.
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# ============================================================
#  Stage 2 — dev: all deps, hot-reload entrypoint
# ============================================================
FROM deps AS dev

# Source is bind-mounted in docker compose. Copying here makes
# the image usable standalone without a volume mount.
COPY --chown=nextjs:nodejs . .

USER nextjs
EXPOSE 3000
ENV PORT=3000 HOSTNAME="0.0.0.0"
CMD ["pnpm", "run", "dev"]

# ============================================================
#  Stage 3 — builder: production Next.js build
# ============================================================
FROM deps AS builder

COPY . .

# NEXT_PUBLIC_ vars are baked into the static bundle at build time.
# They must be passed as build args — runtime env vars have no effect.
ARG BACKEND_URL
ENV BACKEND_URL=$BACKEND_URL

ENV NODE_ENV=production

# Requires next.config.js to have: output: 'standalone'
# Standalone mode bundles only what's needed — ~5x smaller than
# copying the full node_modules into the production image.
RUN pnpm run build

# ============================================================
#  Stage 4 — runner: minimal production image
# ============================================================
FROM base AS runner

ENV NODE_ENV=production

# Standalone output is a self-contained server with the minimal
# subset of node_modules needed at runtime.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000
ENV PORT=3000 HOSTNAME="0.0.0.0"

# Uses wget (installed in base) — no curl needed.
HEALTHCHECK --interval=10s --timeout=5s --retries=3 \
    CMD wget -qO- http://localhost:3000/api/health || exit 1

# server.js is generated by Next.js standalone output.
CMD ["node", "server.js"]