name: 1. CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  ci:
    uses: Nicola-Ibrahim/Tracing-Objectives-Backwards-Devops/.github/workflows/reusable-ci-node.yml@main
    with:
      node-version: '20'
      package-manager: 'pnpm'